Repository cupy/cupy-release-tools, pull requests merged in 2021-03, with the labels that each got.

#79 Install cuDNN in `dist.py` using `cupyx.tools.install_library` on Windows
  .pfnci/wheel-windows/README.md
  .pfnci/wheel-windows/_error_handler.ps1
  .pfnci/wheel-windows/_flexci.ps1
  .pfnci/wheel-windows/build.ps1
  .pfnci/wheel-windows/install_cudnn.ps1
  .pfnci/wheel-windows/main.bat
  dist.py
Labels: blocker

#83 Add name to workflow
  .github/workflows/pretest.yml
Labels: st:to-be-backported

#85 [backport] Add name to workflow
  .github/workflows/pretest.yml
Labels: backport

#84 [v8] Fix submit script for v8
  .pfnci/wheel-windows/submit.sh
Labels: blocking

#81 Support preloading cuTENSOR and NCCL
  .pfnci/test.sh
  .pfnci/wheel-windows/submit.sh
  README.rst
  build.sh
  builder/Dockerfile
  builder/agent.py
  builder/setup_cuda_opt_lib.py
  builder/setup_python.sh
  dist.py
  dist_config.py
  download_nccl.sh
  jenkins.sh
  release-tests/pkg_wheel/test_preload.py
  verifier/Dockerfile.debian
  verifier/Dockerfile.rhel
  verifier/agent.py
Labels: blocking

#87 Catch preload warnings as error on verification
  verifier/agent.py
Labels: to-be-backported

#88 [backport] Catch preload warnings as error on verification
  verifier/agent.py
Labels: backport

#82 Build Linux wheels on FlexCI
  .pfnci/config.pbtxt
  .pfnci/wheel-linux/main.sh
  .pfnci/wheel-linux/submit.sh
Labels: to-be-backported

#89 [backport] Build Linux wheels on FlexCI
  .pfnci/config.pbtxt
  .pfnci/wheel-linux/main.sh
  .pfnci/wheel-linux/submit.sh
Labels: backport

#93 Use the latest flake8
  .github/workflows/pretest.yml
Labels: to-be-backported

#90 Fix cuda_lib directory missing in sdist build
  .pfnci/wheel-linux/main.sh
  builder/setup_cuda_opt_lib.py
  dist.py
  dist_config.py
Labels: blocking

#97 [v8] Download nccl in v8 and fix tests
  .pfnci/config.pbtxt
  .pfnci/wheel-linux/main.sh
Labels: blocking

#95 [backport] Use the latest flake8
  .github/workflows/pretest.yml
Labels: backport

#92 Add PyPI asset checker
  check_pypi_assets.py
Labels: to-be-backported

#99 [backport] Add PyPI asset checker
  check_pypi_assets.py
Labels: backport

#94 Check version before starting a build
  dist.py
  dist_config.py
Labels: to-be-backported

#91 Filter warnings on import test
  verifier/agent.py
Labels: to-be-backported

#103 [backport] Filter warnings on import test
  verifier/agent.py
Labels: backport

#102 [backport] Check version before starting a build
  dist.py
  dist_config.py
Labels: backport
