Repository cupy/cupy-release-tools, pull requests merged in 2021-05, with the labels that each got.

#115 [backport] Add support for ROCm 4.2
  builder/Dockerfile
  dist_config.py
  verifier/Dockerfile.rhel
Labels: backport

#114 Dont error if cutensor is not installed
  .pfnci/wheel-windows/build.ps1
Labels: blocking

#112 fix nccl preload test version
  release-tests/pkg_wheel/test_preload.py
Labels: blocking

#117 [backport] Dont error if cutensor is not installed
  .pfnci/wheel-windows/build.ps1
Labels: backport, blocking

#116 [backport] fix nccl preload test version
  release-tests/pkg_wheel/test_preload.py
Labels: backport, blocking

#119 Improved tagline
  dist_config.py
Labels: to-be-backported

#122 [backport] Improved tagline
  dist_config.py
Labels: backport

#127 [backport] Remove setuptools version restriction
  verifier/Dockerfile.debian
  verifier/Dockerfile.rhel
Labels: backport

#128 Update assets checker
  check_pypi_assets.py
Labels: to-be-backported

#129 [backport] Update assets checker
  check_pypi_assets.py
Labels: backport
