Repository cupy/cupy-release-tools, pull requests merged in 2022-03, with the labels that each got.

#236 Support CUDA 11.6
  .pfnci/build_submit.sh
  .pfnci/config.pbtxt
  .pfnci/wheel-linux/main.sh
  .pfnci/wheel-windows/_flexci.ps1
  builder/base/cuda-runfile/build.sh
  check_release_assets.py
  dist_config.py
Labels: to-be-backported, blocking

#245 [backport] Support CUDA 11.6
  .pfnci/build_submit.sh
  .pfnci/config.pbtxt
  .pfnci/wheel-linux/main.sh
  .pfnci/wheel-windows/_flexci.ps1
  builder/base/cuda-runfile/build.sh
  check_release_assets.py
  dist_config.py
Labels: backport, blocking

#246 Respect shebang to run CI
  .pfnci/config.pbtxt
  .pfnci/wheel-linux/main.sh
Labels: to-be-backported

#248 [backport] Respect shebang to run CI
  .pfnci/config.pbtxt
  .pfnci/wheel-linux/main.sh
Labels: backport

#237 Support ROCm 5.0
  .pfnci/config.pbtxt
  README.rst
  check_release_assets.py
  dist_config.py
  verifier/Dockerfile.debian
Labels: to-be-backported, blocking

#249 [backport] Support ROCm 5.0
  .pfnci/config.pbtxt
  README.rst
  check_release_assets.py
  dist_config.py
  verifier/Dockerfile.debian
Labels: backport, blocking

#251 [backport] Fix verifier for ROCm 4.3
  verifier/Dockerfile.debian
Labels: backport

#252 Fix verifier for ROCm 4.3 (`LLVM_PATH` still needed)
  verifier/Dockerfile.debian
Labels: to-be-backported

#253 [backport] Fix verifier for ROCm 4.3 (`LLVM_PATH` still needed)
  verifier/Dockerfile.debian
Labels: backport
