Repository cupy/cupy-release-tools, pull requests merged in 2022-06, with the labels that each got.

#261 [backport] Add aarch64 wheel build feature for CUDA 11.6
  builder/Dockerfile.el8
  builder/base/cuda-runfile/build.sh
  dist.py
  dist_config.py
  verifier/Dockerfile.el8
Labels: backport

#258 Add CUDA 11.5 aarch64 support
  builder/base/cuda-runfile/Dockerfile
  builder/base/cuda-runfile/build.sh
  dist_config.py
Labels: to-be-backported

#263 [backport] Add CUDA 11.5 aarch64 support
  builder/base/cuda-runfile/Dockerfile
  builder/base/cuda-runfile/build.sh
  dist_config.py
Labels: backport

#260 Add options to build/push docker images for builder/verifier
  dist.py
Labels: to-be-backported

#264 [backport] Add options to build/push docker images for builder/verifier
  dist.py
Labels: backport

#266 Fix verifier for ubi8
  verifier/Dockerfile.el8
Labels: to-be-backported

#267 [backport] Fix verifier for ubi8
  verifier/Dockerfile.el8
Labels: backport

#257 Support CUDA 11.7
  .pfnci/build_submit.sh
  .pfnci/config.pbtxt
  .pfnci/wheel-linux/main.sh
  .pfnci/wheel-linux/update-cuda-driver.sh
  .pfnci/wheel-windows/_flexci.ps1
  builder/base/cuda-runfile/build.sh
  check_release_assets.py
  dist_config.py
Labels: to-be-backported

#270 [backport] Support CUDA 11.7
  .pfnci/build_submit.sh
  .pfnci/config.pbtxt
  .pfnci/wheel-linux/main.sh
  .pfnci/wheel-linux/update-cuda-driver.sh
  .pfnci/wheel-windows/_flexci.ps1
  builder/base/cuda-runfile/build.sh
  check_release_assets.py
  dist_config.py
Labels: backport

#269 Add `cupy-cuda11x` wheel configuration
  .pfnci/wheel-windows/_flexci.ps1
  dist_config.py
Labels: blocking

#271 Update long description for `cupy-cuda11x` wheel
  dist_config.py
Labels: blocking

#262 Improve build of CUDA 10.2 Jetson wheels
  builder/base/cuda-10.2-jetson/.dockerignore
  builder/base/cuda-10.2-jetson/build.sh
  dist_config.py
Labels: to-be-backported

#275 [backport] Improve build of CUDA 10.2 Jetson wheels
  builder/base/cuda-10.2-jetson/.dockerignore
  builder/base/cuda-10.2-jetson/build.sh
  dist_config.py
Labels: backport

#279 [backport] Remove Jeston wheels build from FlexCI
  .pfnci/build_submit.sh
Labels: backport
