Repository cupy/cupy-release-tools, pull requests merged in 2022-08, with the labels that each got.

#292 [backport] Remove cupy-rocm-4-2
  dist_config.py
Labels: backport

#291 Update check_release_assets.py for v11.0.0 release
  check_release_assets.py
Labels: to-be-backported

#294 [backport] Update check_release_assets.py for v11.0.0 release
  check_release_assets.py
Labels: backport

#293 Use `SimpleScrapingLocator`
  check_release_assets.py
Labels: to-be-backported

#296 [backport] Use `SimpleScrapingLocator`
  check_release_assets.py
Labels: backport

#298 Bump version to v12
  dist_config.py
Labels: blocking

#300 [backport] Fix verify images
  dist_config.py
Labels: backport
