Repository cupy/cupy-release-tools, pull requests merged in 2023-10, with the labels that each got.

#366 Preserve symlinks in source tree
  .pfnci/wheel-windows/_flexci.ps1
  .pfnci/wheel-windows/build.ps1
  dist.py
Labels: to-be-backported, blocking

#367 [backport] Preserve symlinks in source tree
  .pfnci/wheel-windows/_flexci.ps1
  .pfnci/wheel-windows/build.ps1
  dist.py
Labels: backport, blocking

#369 remove packages to be dropped in v13
  dist_config.py
Labels: blocking

#368 Add support for Python 3.12 wheel
  .pfnci/build_submit.sh
  .pfnci/config.pbtxt
  .pfnci/wheel-windows/_flexci.ps1
  check_release_assets.py
  dist_config.py
  dist_utils.py
Labels: to-be-backported, blocking

#370 [backport] Add support for Python 3.12 wheel
  .pfnci/build_submit.sh
  .pfnci/config.pbtxt
  .pfnci/wheel-windows/_flexci.ps1
  check_release_assets.py
  dist_config.py
  dist_utils.py
Labels: backport, blocking
