Repository cupy/cupy-release-tools, pull requests merged in 2023-07, with the labels that each got.

#352 Drop support for Python 3.8
  .pfnci/build_submit.sh
  .pfnci/config.pbtxt
  dist_config.py
Labels: blocking

#350 Drop support for CUDA 11.1 or earlier
  dist_config.py
Labels: blocking

#351 Bump base images for verification
  dist_config.py
  verifier/Dockerfile.debian
Labels: to-be-backported, blocking

#353 [backport] Bump base images for verification
  dist_config.py
  verifier/Dockerfile.debian
Labels: backport, blocking

#354 Fix Cython version used for build
  .pfnci/wheel-windows/build.ps1
  dist_config.py
Labels: to-be-backported

#355 Support CUDA 12.2
  .pfnci/wheel-windows/_flexci.ps1
  builder/base/cuda-runfile/build.sh
  dist_config.py
Labels: to-be-backported

#356 [backport] Fix Cython version used for build
  .pfnci/wheel-windows/build.ps1
  dist_config.py
Labels: backport

#357 [backport] Support CUDA 12.2
  .pfnci/wheel-windows/_flexci.ps1
  builder/base/cuda-runfile/build.sh
  dist_config.py
Labels: backport
