Repository cupy/cupy-release-tools, pull requests merged in 2025-03, with the labels that each got.

#403 Replace `nvidia-docker run` with `docker run --gpus=all`
  README.rst
  dist.py
Labels: to-be-backported

#409 [backport] Replace `nvidia-docker run` with `docker run --gpus=all`
  README.rst
  dist.py
Labels: backport

#408 Use `_generate_wheel_metadata.py`
  dist.py
Labels: to-be-backported, blocking

#410 [backport] Use `_generate_wheel_metadata.py`
  dist.py
Labels: backport, blocking
