Repository cupy/cupy-release-tools, pull requests merged in 2025-06, with the labels that each got.

#427 Support CUDA 12.9
  .pfnci/wheel-windows/_flexci.ps1
  builder/base/cuda-runfile/build.sh
  dist_config.py
  verifier/Dockerfile.debian
Labels: to-be-backported

#430 [backport] Support CUDA 12.9
  .pfnci/wheel-windows/_flexci.ps1
  builder/base/cuda-runfile/build.sh
  dist_config.py
  verifier/Dockerfile.debian
Labels: backport

#428 Fix sdist verification not working
  dist.py
Labels: to-be-backported, blocking

#432 [backport] Fix sdist verification not working
  dist.py
Labels: backport, blocking

#433 Fix sdist verification failing
  verifier/agent.py
Labels: to-be-backported, blocking

#434 [backport] Fix sdist verification failing
  verifier/agent.py
Labels: backport, blocking
