Repository cupy/cupy-release-tools, pull requests merged in 2025-07, with the labels that each got.

#436 Support preloading setup of aarch64 wheels
  dist.py
  dist_config.py
Labels: to-be-backported, blocking

#438 Fix CUDA version passed to `_generate_wheel_metadata.py` tool
  dist.py
Labels: to-be-backported, blocking

#440 [backport] Fix CUDA version passed to `_generate_wheel_metadata.py` tool
  dist.py
Labels: backport, blocking

#444 [backport] Fix invalid long description env var name
  dist.py
Labels: backport, blocking

#447 [backport] Update builder dependencies
  builder/setup_python.sh
Labels: backport

#448 Fix requirements to run release tools
  builder/setup_python.sh
  requirements.txt
Labels: to-be-backported

#452 [backport] Bump CUDA version used at build time for aarch64 wheel
  dist_config.py
Labels: backport

#451 Update `ENV` usage in Dockerfiles
  builder/Dockerfile
  builder/Dockerfile.el8
  builder/base/cuda-runfile/Dockerfile
  verifier/Dockerfile.debian
  verifier/Dockerfile.el8
  verifier/Dockerfile.rhel
Labels: to-be-backported

#453 [backport] Update `ENV` usage in Dockerfiles
  builder/Dockerfile
  builder/Dockerfile.el8
  builder/base/cuda-runfile/Dockerfile
  verifier/Dockerfile.debian
  verifier/Dockerfile.el8
  verifier/Dockerfile.rhel
Labels: backport
